### ISSUE TITLE
Crash after prolonged use

### ISSUE THREAD

**Issue by ransagy** [cerebrate/wabash#11]
I've been running wabash 0.6.4.0 with the latest daemon (5?) for a day or so, On Windows 10 Pro x64 build 16232 (Insider Preview of Fall Update) with the latest xenial WSL build (16.04.2).

It's been using its default configurations, and i utilize it to run cronjob on start/windows login - which runs my ZNC IRC bouncer instance.

Today, after a day or running, wabash crashed with the following stack:

`Application: Wabash.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at ArkaneSystems.Wabash.DaemonManager.<InputReader>z__OriginalMethod(System.IO.StreamReader)
   at ArkaneSystems.Wabash.DaemonManager+<InputReader>c__Binding.Invoke(System.Object ByRef, PostSharp.Aspects.Arguments, System.Object)
   at PostSharp.Aspects.Internals.MethodBinding.PostSharp.Aspects.IMethodBinding.Invoke(System.Object ByRef, PostSharp.Aspects.Arguments)
   at PostSharp.Patterns.Threading.WorkItem.Invoke(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
`

and the following event viewer log:

`Faulting application name: Wabash.exe, version: 0.6.4.0, time stamp: 0x58175719
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007fff13e89db0
Faulting process id: 0x20c8
Faulting application start time: 0x01d3098af3561e67
Faulting application path: C:\Software\Wabash\Wabash.exe
Faulting module path: unknown
Report Id: a9a8f98a-60b8-4de4-a4af-ffefb53b0b05
Faulting package full name: 
Faulting package-relative application ID: `

Let me know if there's anything else i can provide and/or test.

**Comment by ransagy** [comment]
I wanted to take a look at this myself and PR if possible, But it seems like it requires a commercial license of PostSharp to do so, sadly.

**Comment by cerebrate** [comment]
@ransagy It should still be small enough to be covered by (the free) PostSharp Essentials, I think, per [this blog post](http://www.postsharp.net/blog/)? Although I confess I haven't tested it myself since the recent licensing change.

**Comment by ransagy** [comment]
@cerebrate I did install and register for the Essentials license, But that doesn't seem to matter. I tried compiling under VS2017 Community.

**Comment by cerebrate** [comment]
@ransagy Sorry for taking so long to get back to you. I hadn't been able to get a good handle on this (for a proper fix, I mean; it happens when the connection between wabash and the WSL session hosting wabashd broke, and I couldn't find a way to handle that that didn't cause the WSL session to terminate), and then the day job ate my brain.

However: I have noticed that this lost-connection problem is no longer happening for me post the Fall Creators' Update. If you're still using wabash and have an updated machine handy, could you let me know if this is the same for you? Thanks.

**Comment by ransagy** [comment]
All my machines have been updated since. I've worked around the issue by having a batch file that makes sure wabash was running. (could have used a schedule task, come to think of it)

I don't think it crashed a lot since, but I'll monitor it and let you know.

**Comment by ransagy** [comment]
@cerebrate So no crashes at all this week, I'm closing this for now, seems solved upstream as you said.
