### ISSUE TITLE
Can't install WSL package

### ISSUE THREAD

**Issue by UndarkAido** [cerebrate/wabash#2]
Here's the error I'm getting:
```
$ sudo dpkg -i wabashd_4_wsl.deb
Selecting previously unselected package wabashd.
(Reading database ... 26122 files and directories currently installed.)
Preparing to unpack wabashd_4_wsl.deb ...
Unpacking wabashd (4) ...
dpkg: dependency problems prevent configuration of wabashd:
 wabashd depends on mono-4.0-service (>= 4.2.1); however:
  Version of mono-4.0-service on system is 3.2.8+dfsg-4ubuntu1.1.
 wabashd depends on mono-runtime (>= 4.2.1); however:
  Version of mono-runtime on system is 3.2.8+dfsg-4ubuntu1.1.

dpkg: error processing package wabashd (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 wabashd
```

I installed the packages it wants manually, but they seem to not be the newest versions?

**Comment by cerebrate** [comment]
Are you on xenial, or still on trusty? Wabashd was written against the xenial packages, so if the latter, that's probably why, and upgrading your WSL to xenial should fix it.

**Comment by UndarkAido** [comment]
I'm on whatever the default is, I'll look into upgrading.

**Comment by cerebrate** [comment]
It'll depend on how long you've had it installed; build 14936 and later have installed xenial by default, but if you had WSL installed from a previous build, it doesn't upgrade it automatically.

`do-release-upgrade` should be all you need.
