### ISSUE TITLE
visudo

### ISSUE THREAD

**Issue by cg-** [cerebrate/wabash#4]
The sudoers line:

`ALL ALL = (root) NOPASSWD: /usr/sbin/service`

in the README didn't work for me. However, 

`%sudo   ALL=(ALL) NOPASSWD:     /usr/sbin/service`

works fine.

**Comment by cerebrate** [comment]
I haven't been able to reproduce this, unfortunately. Any more details on the problem you ran into would be appreciated!

**Comment by cg-** [comment]
Went off a fresh install of Windows, and also wasn't able to reproduce the problem. I think it might have just been something with that specific machine.
