### ISSUE TITLE
Could not start wabashd.

### ISSUE THREAD

**Issue by richardlock** [cerebrate/wabash#5]
Hi,

Thanks for your work on wabash.  I've installed wabash using chocolatey, and wabashd from the wsl-translinux repo.  My WSL release is 16.04.1 LTS.  When I try to launch wabash.exe, it gives error:

![image](https://cloud.githubusercontent.com/assets/9743186/21716361/fc7891ae-d401-11e6-9a23-9ee965e86cfe.png)

If I try to manually run start-wabashd in WSL, I get the following error:

version: 4
shell: /bin/bash
Error: /proc must be mounted
  To mount /proc at boot you need an /etc/fstab line like:
      proc   /proc   proc    defaults
  In the meantime, run "mount proc /proc -t proc"
sess: -1 daem: 0

Is there something else I need to do to get wabash working?

Thanks, Richard

**Comment by richardlock** [comment]
I have tried clearing the lock file which has been present once or twice.

**Comment by cerebrate** [comment]
That's odd. It looks like wabashd is having trouble (or rather, ps, which wabashd uses, is) getting the list of running processes. Can you send me the output of the following commands in your WSL:

_ps --ppid 1 --no-headers -o comm_

_ls /proc_

and

_mount_

? Thanks.

**Comment by richardlock** [comment]
Thanks.

$ ps --ppid 1 --no-headers -o comm
Error: /proc must be mounted
  To mount /proc at boot you need an /etc/fstab line like:
      proc   /proc   proc    defaults
  In the meantime, run "mount proc /proc -t proc"

$ ls /proc
1  17  2  cmdline  cpuinfo  filesystems  interrupts  loadavg  meminfo  mounts  net  self  stat  sys  uptime  version

$ mount
rootfs on / type rootfs (rw,relatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=204320k,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
none on /run/shm type tmpfs (rw,nosuid,nodev,relatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,relatime,size=102400k,mode=755)

**Comment by cerebrate** [comment]
Hm. I'll say up front that this looks to me like something's gone fairly fundamentally wrong with your WSL installation (if ps isn't working even from the command line, it's not a wabash-specific problem). You could try seeing if _ps_ works as root, or do an _strace ps_ to see if the problem shows up there, but unless you've got a lot of un-backuped customization done to WSL, I'd be tempted to just uninstall and reinstall it to clear this up.

**Comment by richardlock** [comment]
Thanks Alistair.  I'll try that.  I wasn't sure if the lack of process visibility was a normal limitation of bash on Windows, but it sounds like an issue on my machine.  I'll check and close if so.  Thanks.

**Comment by richardlock** [comment]
It was my upgrade to 16.04 which killed WSL rather than using the Insider Preview build.  Sorry about that.  Thanks for your help.  Richard
