### ISSUE TITLE
No wabash package in repo

### ISSUE THREAD

**Issue by slikts** [cerebrate/wabash#7]
Following the instructions, I've added the https://cerebrate.github.io/wsl-translinux repo and updated (I get the notice about unsigned repo), but there's no wabash package:

> $ apt-cache policy wabash
> N: Unable to locate package wabash

**Comment by cerebrate** [comment]
Oops, looks like you found a typo in the instructions, now fixed. The package you need to install from the repo is _wabashd_, rather than _wabash_. Sorry 'bout that.
